### ISSUE TITLE
Member Types Relationship

### ISSUE THREAD

**Issue by espellcaste** [lmoffereins/bp-xprofile-relationship-field#1]
What about the new Member Type? Although being private, I think it should be interesting to have it.

**Comment by lmoffereins** [comment]
Are you suggesting to relate users to member types through this plugin? The thing is, though Member Types are a user taxonomy (`bp_member_type`), this plugin does not create native user-term relationships the WordPress taxonomy way. In fact, the connections created through the Relationship field are stored in XProfile data. So the BP's new member type functions will not be able to connect with it - it would not be compatible with the way the Member Types API is set up.

However, if you'd like to still do this, you can always add your custom relationship type through the filters available in the plugin. Here is an implementation of how that would look like:

Append Member Types to relationship type selection

``` php
function bpxprf_add_member_types_relationship( $relationships ) {
    $relationships['other']['options']['member_types'] = __( 'Member Types', 'your-plugin' );

    return $relationships;
}
add_filter( 'bp_xprofile_relationship_field_relationships', array( $this, 'bpxprf_add_member_types_relationship' ) );
```

Setup collection of Member Type options to choose from

``` php
function bpxprf_list_member_type_options( $options, $object, $field, $args ) {
    if ( 'member_types' != $object )
        return $options;

    // Get all member types
    $types = bp_get_member_types( array(), 'objects' );

    // Setup member types properly
    foreach ( $types as $type ) {
        $options[] = (object) array( 'id' => $type->name, 'name' => $type->labels['singular_name'] );
    }

    return $options;
}
add_filter( 'bp_xprofile_get_relationship_field_options_custom', array( $this, 'bpxprf_list_member_type_options' ), 10, 4 );
```

Display selected Member Type of the user

``` php
function bpxprf_display_user_member_type( $value, $option, $field ) {
    if ( 'member_type' != $field->related_to )
        return $value;

    $member_type = bp_get_member_type_object( $value );

    return $member_type->labels['singular_name'];
}
add_filter( 'bp_xprofile_relationship_field_option_value', 'bpxprf_display_user_member_type', 10, 3 );
```

I did not extensively test the previous code, but I hope this helps you on your way.

**Comment by espellcaste** [comment]
Thanks for the code, but it won't solve my problem. 

At first I was considering your plugin but I decided to take another route.

I created a radio box field and depending of the value, I'm setting the member type through bp_core_signup_user().

Thanks anyway! =)
